# CLIP多模态文本-图像联邦学习配置文件
# 专门用于文本-图像多模态联邦学习实验

# ==============================
# 实验基本设置
# ==============================
experiment:
  name: "clip_multimodal_federated"        # 实验名称
  rounds: 15                               # 多模态需要适中的轮数
  seed: 42                                 # 随机种子

# ==============================
# 设备配置
# ==============================
device: "auto"  # auto: 自动检测GPU, cuda: 强制GPU, cpu: 强制CPU

# ==============================
# 分布式训练和日志配置
# ==============================
wandb:
  enabled: false                           # 调试阶段关闭WandB
  project: "clip-multimodal-federated"     # 多模态专用项目
  offline: false                           # 不使用离线模式

# ==============================
# 客户端配置
# ==============================
client:
  num_clients: 1                           # 单客户端，专注于多模态能力验证
  local_epochs: 2                          # 本地训练轮数
  learning_rate: 0.00005                   # CLIP适用的学习率
  
  # 客户端数据集分配 - 单客户端多数据集
  client_datasets:
    client_0:
      - mnist                              # 包含多种数据模态
      - cifar10

# ==============================
# 服务器配置
# ==============================
server:
  aggregation_method: "federated_avg"      # FedAvg算法
  server_learning_rate: 1.0                # 服务器学习率

# ==============================
# 模型配置
# ==============================
model:
  type: "clip"                             # CLIP多模态模型
  learning_rate: 0.00005                   # 模型学习率
  
  # Hugging Face模型配置
  model_name: "openai/clip-vit-base-patch32"  # 预训练CLIP模型
  cache_dir: "/home/zzm/checkpoint"        # 模型缓存目录
  use_pretrained: true                     # 使用预训练权重
  
  # CLIP特有参数
  temperature: 0.07                        # 对比学习温度参数
  freeze_vision_encoder: false             # 不冻结视觉编码器
  freeze_text_encoder: false               # 不冻结文本编码器
  
  # 图像编码器配置
  image_encoder:
    feature_dim: 768                       # ViT-B/32特征维度
  
  # 文本编码器配置
  text_encoder:
    feature_dim: 512                       # 文本特征维度
    max_length: 77                         # 最大文本序列长度

# ==============================
# 优化器配置
# ==============================
optimizer:
  type: "adamw"                            # 优化器类型
  learning_rate: 5e-5                      # CLIP推荐学习率
  weight_decay: 0.1                        # 较大的权重衰减
  betas: [0.9, 0.98]                      # CLIP优化专用beta参数
  eps: 1e-8                               # 数值稳定性参数

# ==============================
# 数据集配置
# ==============================
data:
  data_dir: "/home/zzm/dataset/"           # 数据集根目录
  batch_size: 16                           # 适合CLIP的批次大小
  num_workers: 2                           # 数据加载器工作进程数
  
  # 具体数据集配置
  datasets:
    mnist:
      train: true                          # MNIST数据集
    cifar10:
      train: true                          # CIFAR-10数据集
    # 以下为专用的多模态数据集配置（暂时注释）
    # clip_dataset:
    #   train: true
    #   image_size: 224
    #   normalize: true
    #   transforms:
    #     resize: 224
    #     center_crop: 224
    #     normalize:
    #       mean: [0.48145466, 0.4578275, 0.40821073]
    #       std: [0.26862954, 0.26130258, 0.27577711]

# ==============================
# 评估配置
# ==============================
evaluation:
  evaluate_every: 1                        # 每轮都评估
  test_batch_size: 32                      # 测试批次大小
  metrics:                                 # 多模态评估指标
    - "loss"
    - "accuracy"
    - "top5_accuracy"                      # Top-5准确率
    - "contrastive_loss"                   # 对比损失
