# 默认联邦学习实验配置文件
# 这是所有其他配置文件的基础模板

# ==============================
# 实验基本设置
# ==============================
experiment:
  name: "federated_learning_experiment"    # 实验名称
  rounds: 10                               # 联邦学习轮数
  seed: 42                                 # 随机种子，确保可重复性

# ==============================
# 设备配置
# ==============================
device: "auto"  # auto: 自动检测GPU, cuda: 强制GPU, cpu: 强制CPU

# ==============================
# 学习率配置 - 统一管理所有学习率设置
# ==============================
learning_rates:
  client: 0.001                            # 客户端学习率
  server: 1.0                              # 服务器聚合学习率
  model: 0.001                             # 模型训练学习率
  optimizer: 0.001                         # 优化器学习率

# ==============================
# 分布式训练和日志配置
# ==============================
wandb:
  enabled: false                           # 是否启用WandB日志
  project: "federated-learning"            # WandB项目名称
  offline: false                           # 是否使用离线模式

# ==============================
# 客户端配置
# ==============================
client:
  num_clients: 5                           # 总客户端数量
  local_epochs: 5                          # 每个客户端本地训练轮数
  
  # 客户端数据集分配 - 定义每个客户端使用的数据集
  client_datasets:
    client_0:
      - mnist
    client_1:
      - mnist
    client_2:
      - mnist
    client_3:
      - mnist
    client_4:
      - mnist
  
# ==============================
# 服务器配置
# ==============================
server:
  aggregation_method: "federated_avg"      # 聚合算法: federated_avg

# ==============================
# 模型配置
# ==============================
model:
  type: "cnn"                              # 模型类型: cnn, linear, clip

# ==============================
# 优化器配置
# ==============================
optimizer:
  type: "adamw"                            # 优化器类型
  weight_decay: 0.01                       # 权重衰减
  betas: [0.9, 0.999]                     # Adam beta参数
  eps: 1e-8                               # 数值稳定性参数

# ==============================
# 数据集配置
# ==============================
data:
  data_dir: "/home/zzm/dataset/"           # 数据集根目录
  batch_size: 32                           # 训练批次大小
  num_workers: 2                           # 数据加载器工作进程数
  
  # 具体数据集配置
  datasets:
    mnist:
      train: true                          # 是否使用训练集
      # test: true                         # 是否使用测试集

# ==============================
# 评估配置
# ==============================
evaluation:
  evaluate_every: 1                        # 每隔多少轮评估一次
  test_batch_size: 100                     # 测试批次大小
  metrics:                                 # 评估指标
    - "loss"
    - "accuracy"
