# MNIST 联邦学习基线实验配置
# 专门用于MNIST数据集的基线实验，遵循联邦学习经典设置

# ==============================
# 实验基本设置
# ==============================
experiment:
  name: "mnist_fedavg_baseline"             # 实验名称
  rounds: 10                               # 联邦学习轮数
  seed: 42                                 # 随机种子

# ==============================
# 设备配置
# ==============================
device: "auto"  # auto: 自动检测GPU, cuda: 强制GPU, cpu: 强制CPU

# ==============================
# 分布式训练和日志配置
# ==============================
wandb:
  enabled: false                           # 是否启用WandB
  project: "federated-learning-baseline"   # WandB项目名称
  offline: true                            # 离线模式，适合基线实验

# ==============================
# 客户端配置
# ==============================
client:
  num_clients: 10                          # 经典联邦学习客户端数量
  local_epochs: 2                          # 本地训练轮数（遵循FedAvg论文设置）
  learning_rate: 0.001                     # 客户端学习率
  
  # 客户端数据集分配 - 所有客户端使用MNIST
  client_datasets:
    client_0:
      - mnist
    client_1:
      - mnist
    client_2:
      - mnist
    client_3:
      - mnist
    client_4:
      - mnist
    client_5:
      - mnist
    client_6:
      - mnist
    client_7:
      - mnist
    client_8:
      - mnist
    client_9:
      - mnist
  
# ==============================
# 服务器配置
# ==============================
server:
  aggregation_method: "federated_avg"      # FedAvg算法
  server_learning_rate: 1.0                # 服务器学习率

# ==============================
# 模型配置
# ==============================
model:
  type: "cnn"                              # CNN模型，适合MNIST
  learning_rate: 0.001                     # 模型学习率

# ==============================
# 优化器配置
# ==============================
optimizer:
  type: "adamw"                            # 优化器类型
  learning_rate: 0.001                     # 学习率
  weight_decay: 0.01                       # 权重衰减
  betas: [0.9, 0.999]                     # Adam beta参数
  eps: 1e-8                               # 数值稳定性参数

# ==============================
# 数据集配置
# ==============================
data:
  data_dir: "/home/zzm/dataset/"           # 数据集根目录
  batch_size: 10                           # 小批次大小（论文中常用设置）
  num_workers: 2                           # 数据加载器工作进程数
  
  # 具体数据集配置
  datasets:
    mnist:
      train: true                          # 使用MNIST训练集

# ==============================
# 评估配置
# ==============================
evaluation:
  evaluate_every: 1                        # 每轮都评估
  test_batch_size: 100                     # 测试批次大小
  metrics:                                 # 评估指标
    - "loss"
    - "accuracy"