# MNIST 联邦学习基线实验配置

# 实验基本设置
experiment:
  name: "mnist_fedavg"
  rounds: 10  
  seed: 42

# 设备配置
device: "auto"  # auto: 自动检测GPU, cuda: 强制GPU, cpu: 强制CPU

# WandB 配置
wandb:
  enabled: false
  project: "federated-learning-baseline"
  offline: true  # 是否离线模式

# 客户端设置
client:
  num_clients: 10      
  local_epochs: 2       # 本地训练轮数
  learning_rate: 0.001   # AdamW学习率
  
  # 客户端数据集配置 - 所有客户端使用MNIST
  client_datasets:
    client_0:
      - mnist
    client_1:
      - mnist
    client_2:
      - mnist
    client_3:
      - mnist
    client_4:
      - mnist
    client_5:
      - mnist
    client_6:
      - mnist
    client_7:
      - mnist
    client_8:
      - mnist
    client_9:
      - mnist
  
# 服务器设置  
server:
  aggregation_method: "federated_avg"  # FedAvg算法
  server_learning_rate: 1.0  # 服务器学习率

# 模型设置
model:
  type: "cnn"  # CNN模型
  learning_rate: 0.001  # AdamW学习率

# 优化器设置 - 统一使用AdamW
optimizer:
  learning_rate: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 0.00000001

# 数据设置
data:
  data_dir: "/home/zzm/dataset/"
  batch_size: 10     # 论文中使用较小的批次大小
  
  # 数据集配置
  datasets:
    mnist:
      train: true

# 评估设置
evaluation:
  evaluate_every: 1  # 每1轮评估一次