# 多数据集客户端实验配置文件

# 实验基本设置
experiment:
  name: "multi_dataset_federated_experiment"
  rounds: 10
  seed: 42

# WandB 配置
wandb:
  enabled: true  # 是否启用WandB
  project: "federated-learning"
  offline: true  # 是否离线模式

# 客户端设置
client:
  num_clients: 4  # 总客户端数量
  local_epochs: 5
  learning_rate: 0.001  # AdamW默认学习率
  
  # 客户端数据集配置
  client_datasets:
    client_0:
      - mnist
    client_1:
      - mnist
    client_2:
      - cifar10
    client_3:
      - mnist
      - cifar10
  
# 服务器设置  
server:
  aggregation_method: "federated_avg"

# 模型设置
model:
  type: "cnn" 
  learning_rate: 0.001  # AdamW默认学习率

# 优化器设置 - 统一使用AdamW
optimizer:
  learning_rate: 0.001
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

# 数据设置
data:
  data_dir: "/home/zzm/dataset/"
  batch_size: 32
  
  # 数据集配置
  datasets:
    mnist:
      train: true
    cifar10:
      train: true

# 评估设置
evaluation:
  evaluate_every: 1  # 每隔多少轮评估一次
  test_batch_size: 100
