# 简单MNIST联邦学习实验配置
# 所有客户端都使用MNIST数据集

# 实验基本设置
experiment:
  name: "simple_mnist_experiment"
  rounds: 5
  seed: 42

# WandB 配置
wandb:
  enabled: false
  project: "federated-learning"

# 客户端设置
client:
  num_clients: 3
  local_epochs: 3
  learning_rate: 0.001
  
  # 客户端数据集配置
  client_datasets:
    client_0:
      - mnist
    client_1:
      - mnist
    client_2:
      - mnist
  
# 服务器设置  
server:
  aggregation_method: "federated_avg"

# 模型设置
model:
  type: "cnn"
  learning_rate: 0.01

# 优化器设置
optimizer:
  learning_rate: 0.01
  weight_decay: 0.01
  betas: [0.9, 0.999]
  eps: 1e-8

# 数据设置
data:
  data_dir: "/home/zzm/dataset/"
  batch_size: 64
  
  # 数据集配置
  datasets:
    mnist:
      train: true

# 评估设置
evaluation:
  evaluate_every: 1
  test_batch_size: 100
